# Generated by Django 5.2.1 on 2025-05-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name (English)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
