# Generated by Django 5.2.1 on 2025-05-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_full_name_ar_profile_full_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_years',
            field=models.IntegerField(blank=True, default=0, help_text='Number of years of teaching experience.', null=True, verbose_name='Years of Experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_year',
            field=models.IntegerField(blank=True, help_text='Year of your graduation.', null=True, verbose_name='Graduation Year'),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, help_text='Your primary field of study.', max_length=255, null=True, verbose_name='Major/Specialization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, help_text='Name of the university you graduated from.', max_length=255, null=True, verbose_name='University Attended'),
        ),
    ]
