# Generated by Django 5.2.1 on 2025-05-20 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_experience_years_profile_graduation_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Course Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Course Levels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Course Title')),
                ('description', models.TextField(verbose_name='Course Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Course Price')),
                ('language', models.CharField(help_text='e.g., English, Arabic, French', max_length=100, verbose_name='Instruction Language')),
                ('categories', models.ManyToManyField(related_name='courses_offered', to='accounts.coursecategory', verbose_name='Categories')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_at_level', to='accounts.courselevel', verbose_name='Level')),
                ('teacher_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_courses', to='accounts.profile', verbose_name='Teacher Profile')),
            ],
            options={
                'verbose_name_plural': 'Teacher Courses',
                'ordering': ['title'],
            },
        ),
    ]
