# Generated by Django 5.2.1 on 2025-05-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_approval_date_profile_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host_user', models.CharField(help_text='The email address used to send emails (e.g., your_gmail@gmail.com)', max_length=255)),
                ('email_host_password', models.CharField(help_text='The App Password for your email host (NOT your main account password)', max_length=255)),
                ('email_host', models.CharField(default='smtp.gmail.com', help_text='SMTP host (e.g., smtp.gmail.com)', max_length=255)),
                ('email_port', models.IntegerField(default=587, help_text='SMTP port (e.g., 587 for TLS, 465 for SSL)')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Use TLS encryption (True for port 587)')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption (True for port 465)')),
                ('default_from_email', models.CharField(blank=True, help_text="Optional: Default 'From' email address if different from host user", max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configuration',
            },
        ),
    ]
