# Generated by Django 5.2.1 on 2025-05-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfiguration',
        ),
    ]
