# Generated by Django 5.2.1 on 2025-05-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercourse',
            name='course_picture',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='video_trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
