# Generated by Django 5.2.1 on 2025-05-21 08:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_teachercourse_course_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachercourse',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Teacher Courses'},
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='categories',
            field=models.ManyToManyField(related_name='courses', to='accounts.coursecategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='accounts.courselevel', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Course Price'),
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='teacher_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.profile', verbose_name='Teacher Profile'),
        ),
    ]
