# Generated by Django 5.2.1 on 2025-05-21 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_teachercourse_options_teachercourse_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='approval_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the application was approved.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this teacher application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teacher_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_teacher_application_pending',
            field=models.BooleanField(default=True, help_text='Is the teacher application awaiting admin approval?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_teacher_approved',
            field=models.BooleanField(default=False, help_text='Has the teacher application been approved by an admin?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Admin who rejected this teacher application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_teacher_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rejection_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the application was rejected.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection, if applicable.', null=True),
        ),
    ]
