# Generated by Django 5.2.1 on 2025-05-21 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_approval_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='accounts.teachercourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Enrolled Course',
                'verbose_name_plural': 'Enrolled Courses',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
