# Generated by Django 5.2.1 on 2025-05-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_allowedcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedcard',
            name='card_number',
            field=models.CharField(help_text='The 16-digit card number.', max_length=20, unique=True),
        ),
    ]
