# Generated by Django 5.2.1 on 2025-05-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_allowedcard_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedcard',
            name='card_number',
            field=models.CharField(help_text='The card number.', max_length=255, unique=True),
        ),
    ]
