# Generated by Django 5.2.1 on 2025-05-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_allowedcard_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercourse',
            name='featured',
            field=models.BooleanField(default=False, help_text='Check to mark this course as featured on the homepage.'),
        ),
    ]
