# Generated by Django 5.2.1 on 2025-05-22 19:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_teachercourse_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolledcourse',
            options={'ordering': ['-enrolled_at'], 'verbose_name': 'Enrolled Course', 'verbose_name_plural': 'Enrolled Courses'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='teachercourse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Teacher Course', 'verbose_name_plural': 'Teacher Courses'},
        ),
        migrations.AlterField(
            model_name='allowedcard',
            name='expiry_year',
            field=models.IntegerField(help_text='Expiry year (e.g., 2025)', validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2035)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_teacher_application_pending',
            field=models.BooleanField(default=False, help_text='Is the teacher application awaiting admin approval?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='course_picture',
            field=models.ImageField(blank=True, default='course_thumbnails/default_course.png', null=True, upload_to='course_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=2, verbose_name='Instruction Language'),
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Course Price'),
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Current publication status of the course.', max_length=20),
        ),
    ]
