# Generated by Django 5.2.1 on 2025-05-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='fee_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
