# Generated by Django 5.2.1 on 2025-05-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_enrolledcourse_fee_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission percentage (e.g., 5.00 for 5%) deducted from course earnings.', max_digits=5),
        ),
    ]
